### ISSUE TITLE
Syncing a file fails with specific contents

### ISSUE THREAD

**Issue by DeanmvSG** [mdyd-dev/marketplace-kit#162] opened 2019-04-04 14:14 UTC
## Expected behavior 
The file syncs correctly

## Actual behavior
The file reports a 403 and errors.  It then also errors for any sync after that, valid or not.  Until you cancel and run sync again

## Steps to reproduce the problem
1. Create a liquid file with the following assign:
`{% assign test = "string%40" | replace: '%40', '@' -%}`
2. Try to sync file, see the following error:
```
Unhandled rejection StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (/usr/local/lib/node_modules/@platform-os/marketplace-kit/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/@platform-os/marketplace-kit/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/@platform-os/marketplace-kit/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/@platform-os/marketplace-kit/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/@platform-os/marketplace-kit/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@platform-os/marketplace-kit/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

Changing the line to something like 
`{% assign test = "string%40" | replace: '%40', '!' -%}`
works correctly, it seems to mainly be the `@`

Deploying a file with the "broken" assign in it works fine, it seems to just be sync.

### Marketplace Kit
v2.7.4
### NodeJs
v8.15.1
### Operating System
macOS v10.14.4

**Comment by ignacy** [comment] 2019-07-02 06:38
I could not reproduce this issue. Probably it was fixed in newer Platform | Marketplace Kit version.

![cantrepro](https://user-images.githubusercontent.com/25693/60489453-ad71d980-9ca4-11e9-8022-12567f7802b8.png)

**Closed by ignacy** 2019-07-02 06:38 UTC
